name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: surajarya0007
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push snake files
        run: |
          chmod 777 dist/*
          cp dist/github-snake.svg /tmp/github-snake.svg
          cp dist/github-snake-dark.svg /tmp/github-snake-dark.svg
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf .
          cp /tmp/github-snake.svg .
          cp /tmp/github-snake-dark.svg .
          git add github-snake.svg github-snake-dark.svg
          git commit -m "Update snake animation"
          git push origin output --force